#!/usr/bin/env ruby

require 'resume_generator'
require 'parser'
require 'local-server'

parser = Parser.new
cli_opts = parser.parse(ARGV)

command = ARGV.shift
resume = ARGV.shift

if resume.nil?
  puts parser.args
  exit
end

resume = File.expand_path(resume)
cli_opts.input = resume

case command
when 'serve'
  generator = ResumeGenerator.new(cli_opts, is_cli: false)
  server = Server.new(generator, cli_opts)
  server.start
when 'build'
  generator = ResumeGenerator.new(cli_opts)
  generator.write
when 'generate'
  generator = ResumeGenerator.new(cli_opts)
  generator.write_template
else
  puts parser.args
end
