#!/usr/bin/env ruby

require_relative '../lib/resume_generator'
require_relative '../lib/parser'
require_relative '../lib/local-server'

command = ARGV.shift
resume = ARGV.shift

parser = Parser.new
opts = parser.parse(command, ARGV)

if resume.nil?
  puts parser.args
  exit
end

resume = File.expand_path(resume)
opts.input = resume

case command
when 'serve'
  generator = ResumeGenerator.new(opts)
  server = Server.new(generator, opts)
  server.start
when 'build'
  generator = ResumeGenerator.new(opts)
  generator.write
when 'generate'
  generator = ResumeGenerator.new(opts)
  generator.generate_template
else
  puts parser.args
end
